services:
  user-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      ES_URL: "http://elasticsearch:9200"
      REDIS_URL: "redis:6379" 
      GIN_MODE: "debug"
    networks:
      - es-net
      - redis
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  
    networks:
      - es-net
    healthcheck: 
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 40s 


  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "|", "grep", "-q", "PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 
      
volumes:
  es_data:
  redis_data:

networks:
  es-net:
  redis: